### ISSUE TITLE
Extra Utils 2

### ISSUE THREAD

**Issue by Eladkay** [ModdersCorner/404-Mod-List#24]
http://minecraft.curseforge.com/projects/extra-utilities/files

**Comment by JorVaCoding** [comment]
@Eladkay ExUtils2 doesn't work on the server. Sincer we're running spongeforge, it crashes (unless sponge or exutils has been updated to work)...
@Lanse505

**Comment by SkySom** [comment]
(We aren't actually running SpongeForge currently) Also don't ping Lanse for server stuff.

**Comment by Eladkay** [comment]
The only creative flight in the pack right now is the p45sword carbon armor. That is ridiculously expensive, doesn't prevent fall damage, is effected by knockback and worst of all: has 720 durability and can't be repaired.
We need exu.

**Comment by JorVaCoding** [comment]
I agreed 123812938129479% with that, I've been wanted to fly for so long... And if we aren't running SF, what's stopping us from using ExUtils, I think it was supposed to be in the pack but we couldnt have it.

**Comment by SkySom** [comment]
We aren't currently running SF. Because I didn't want to deal with SF and the 1.10.2 update. Though it can be considered. But really guys? You want a mod just cause creative flight... is too expensive. This will definitely need a few more people to agree before we put it on over putting SF on. Which was requested by gabizou

**Comment by Lanse505** [comment]
Like ExtraUtils does have alot of nice features, but I would rather have SF on the server and help test both for mod authors if they're mods are compatible with SF aswell as to see if there are any interaction/issues that the Sponge Team needs to be informed about.

ExtraUtils is nice but if you just want it for creative flight i'm gonna vote no.
Either way it's a No from me simply cause I would perfer us having SF on the server for testing rather than 1 singular mod.

**Comment by srs-bsns** [comment]
I like ExtraUtils for everything BUT the flight. TBH, I've never really used the rings because I've always had some form of jetpack mod installed. Creative flight is too OP. :)

ExtraUtils has a lot of nice features (if they still exist in the latest version), such as:

* the drums
* the spikes
* some of the building blocks
* the transfer nodes that can be used as cobble generators
* some of the power generators are nice as well
* the ender quarry goes without saying

However, unless someone needs to test mod compatibility with it, should it even get added?

**Comment by SkySom** [comment]
The server isn't only for testing the mods themselves. It's also for using them with other mods, as you would on a server.

**Comment by srs-bsns** [comment]
>The server isn't only for testing the mods themselves. It's also for using them with other mods, as you would on a server.

Hence my last sentence. If mod authors, whose mods are on the server, need to test compatibility with it, then it should be added. But if the only reason for adding it is to use some feature of it other than for testing, then it should get a low priority, because the purpose of the server is for mod testing, is it not?

**Comment by warlordjones** [comment]
:-1: Not a fan of creative flight myself.

**Comment by SkySom** [comment]
That's basically how it's currently working.  Any mod put forward by a member of the server gets first dibs, followed by discord members, then any additional ones that the server would like added. The first two don't need a vote, the third does

**Comment by yrsegal** [comment]
I feel like this is a pretty ok addition. Creative flight isn't *that* powerful considering we're going to have Psi on the server...

**Comment by JorVaCoding** [comment]
Creative flight is super helpful to some people... @warlordjones You live underground, it's not helpful for you much... I live with tall roofs, and plan on making an industrial tower base, without creative flight, it's annoying. It's not over powered, just more of a utility.

**Comment by yrsegal** [comment]
If someone with a pair of metal pants on can run across the sky, let people fly across it too.

**Comment by JorVaCoding** [comment]
Oh: and ExUtils2 flight now requires a power system to be made first, so it's not just craft and fly, its power based....

@Lanse505 @SkySom This can also replace FTBLib and Util, it has chunkloading in it. So we can hit two birds with one stone. Reduce mod count with balanced features.

**Comment by SkySom** [comment]
But there is still the fact that unless it's changed, it's not compatible with Sponge? (Which note I said currently, not that it's not being added), and we also have a thing out for Botania being added, which iirc does also add some flight, no?

**Comment by yrsegal** [comment]
The flugel tiara is extremely endgame, and Psi also provides flight of a sort.

**Comment by SkySom** [comment]
Creative flight should be extremely end game, no?

**Comment by JorVaCoding** [comment]
I say mid-game... To me, creative flight isn't over powered like say 10k rf/t, its more of a utility. We could always get a crafting tweaker and change the recipe.
But I feel like the server isn't having "hard-mode" recipes or gameplay. Everything is quite easy to progress through (except for endermen...). It's meant to test mods and have some fun, not spend 5 hours trying to get something.

**Comment by yrsegal** [comment]
except for endermen? Psi's gotcha covered.

**Comment by JorVaCoding** [comment]
1.9 buffed enderman, then quark made them more buffed...

**Comment by yrsegal** [comment]
Psi still has... means.

**Comment by JorVaCoding** [comment]
So does TiCon, EnderIO... It was just hard early game.

**Comment by Eladkay** [comment]
We don't have a whole ton of known mods on the server. EnderIO is one, Tinker's is one, Refined Storage maybe, and that's _about_ it. Extra Utils, along with Botania, Psi and Blood Magic (which are all approved already) will be great for more known mods.
